### ISSUE TITLE
Cannot install this Add-On

### ISSUE THREAD

**Issue by ssditt** [fl4p/influxdb-udp-relay#3]
[supervisor_2024-03-14T08-56-45.167Z.log](https://github.com/fl4p/influxdb-udp-relay/files/14599741/supervisor_2024-03-14T08-56-45.167Z.log)
I have new installation of HA on Hyper-V.vhdx:
Core 2024.3.0
Supervisor 2024.03.0
Operating System 12.0
Frontend 20240306.0
Just successfuly added Mosquito and InfluxDb.
But trying install InfluxDb-udp-relay I get error ERROR (MainThread) [supervisor.docker.addon] Can't build 2af0a32d/amd64-addon-influxdb-udp-relay:0.12: The command '/bin/ash -o pipefail -c pip3 install -r requirements.txt' returned a non-zero code: 1
Full log attached. Complete restart doesn§t help.

**Comment by fl4p** [comment]
This is very likely pip refusing to install global packages. Need to create a virtual environment and install the requirements there.
Fill fix this with the next update

**Comment by ssditt** [comment]
Fabien, thanks for your help!

I found your tool very useful, because InfluxDb with UDP Line Protocol is great to collect data from our self-developed IoT stuff.

And I can just repeat it is a pity the InfluxDb HA-AddOn does not support UDP directly and Franck does not want to spend time with this.

Thanks!

Slavomir

**Comment by fl4p** [comment]
Hi Slavomir,
I just pushed a fix. Please try the update and tell me if it works.

**Comment by ssditt** [comment]
Fabian, THANKS!
Installation OK with ver.0.13. I will test the data pass-through soon.
